### PR TITLE
Fix SoverB and add text “3#sigma”

### PR DESCRIPTION
**Pull request by Libeiyu**

### CODE REVIEW

**Comment by Libeiyu** [comment]
Hi @stefanopolitano! Here, I fixed the S/B and added the text. Maybe we can check if this is correct.

**Comment by stefanopolitano** [comment]
Hi @Libeiyu ! Thanks for the contribution. I approve it, but let's check offline it provides the correct values with this fix

**Comment by Libeiyu** [comment]
> Hi @Libeiyu ! Thanks for the contribution. I approve it, but let's check offline it provides the correct values with this fix

I test this locally, and it's correct. Thank you for the cross-check

**Comment by Libeiyu** [comment]
> Hi @Libeiyu ! Thanks for the contribution. I approve it, but let's check offline it provides the correct values with this fix

But here we also need to check if we are using rawyield as a signal (I've seen it done in some code.) and then if we need to use our given NsigmaforSideband as a parameter for calculating the number of backgrounds.

**Pull request merged**
